from tkinter import *

def click(event):
	text=event.widget.cget("text")
	print(text)
	if text=="=":
		if scvalue.get().isdigit():
			value=int(scvalue.get())
		else:
			value=eval(screen.get())
	elif text=="C":
		scvalue.set("")
		screen.update()
	else:
		scvalue.set(scvalue.get()+text)
		scvalue.update()
	scvalue.set(value)
	screen.update()
	


root=Tk()
root.title("Python Calculator")
scvalue=StringVar()
scvalue.set("")
screen=Entry(root,font=("arial",25,"bold"),text=scvalue,fg='red',bg='white',justify='right',bd=10)
screen.pack()

root.geometry("400x700")
f=Frame(root,borderwidth=6,bg="grey",relief=SUNKEN)
b=Button(f,fg="red", text="9",padx=18,pady=15,font="lucida 20 bold")
b.pack(side=LEFT,padx=5,pady=2)
b.bind("<Button-1>",click)
b=Button(f,fg="red", text="8",padx=18,pady=15,font="lucida 20 bold")
b.pack(side=LEFT,padx=5,pady=2)
b.bind("<Button-1>",click)
b=Button(f,fg="red", text="7",padx=18,pady=15,font="lucida 20 bold")
b.pack(side=LEFT,padx=5,pady=2)
b.bind("<Button-1>",click)
f.pack()
f=Frame(root,borderwidth=6,bg="grey",relief=SUNKEN)
b=Button(f,fg="red", text="6",padx=18,pady=15,font="lucida 20 bold")
b.pack(side=LEFT,padx=5,pady=2)
b.bind("<Button-1>",click)
b=Button(f,fg="red", text="5",padx=18,pady=15,font="lucida 20 bold")
b.pack(side=LEFT,padx=5,pady=2)
b.bind("<Button-1>",click)
b=Button(f,fg="red", text="4",padx=18,pady=15,font="lucida 20 bold")
b.pack(side=LEFT,padx=5,pady=2)
b.bind("<Button-1>",click)
f.pack()
f=Frame(root,borderwidth=6,bg="grey",relief=SUNKEN)
b=Button(f,fg="red", text="3",padx=18,pady=15,font="lucida 20 bold")
b.pack(side=LEFT,padx=5,pady=2)
b.bind("<Button-1>",click)
b=Button(f,fg="red", text="2",padx=18,pady=15,font="lucida 20 bold")
b.pack(side=LEFT,padx=5,pady=2)
b.bind("<Button-1>",click)
b=Button(f,fg="red", text="1",padx=18,pady=15,font="lucida 20 bold")
b.pack(side=LEFT,padx=5,pady=2)
b.bind("<Button-1>",click)
f.pack()
f=Frame(root,borderwidth=6,bg="grey",relief=SUNKEN)
b=Button(f,fg="red", text="0",padx=18,pady=15,font="lucida 20 bold")
b.pack(side=LEFT,padx=5,pady=2)
b.bind("<Button-1>",click)
b=Button(f,fg="red", text="+",padx=18,pady=15,font="lucida 20 bold")
b.pack(side=LEFT,padx=5,pady=2)
b.bind("<Button-1>",click)
b=Button(f,fg="red", text="-",padx=21,pady=15,font="lucida 20 bold")
b.pack(side=LEFT,padx=5,pady=2)
b.bind("<Button-1>",click)
f.pack()
f=Frame(root,borderwidth=6,bg="grey",relief=SUNKEN)
b=Button(f,fg="red", text="*",padx=21,pady=15,font="lucida 20 bold")
b.pack(side=LEFT,padx=5,pady=2)
b.bind("<Button-1>",click)
b=Button(f,fg="red", text="/",padx=18,pady=15,font="lucida 20 bold")
b.pack(side=LEFT,padx=5,pady=2)
b.bind("<Button-1>",click)
b=Button(f,fg="red", text="%",padx=18,pady=15,font="lucida 20 bold")
b.pack(side=LEFT,padx=5,pady=2)
b.bind("<Button-1>",click)
f.pack()
f=Frame(root,borderwidth=6,bg="grey",relief=SUNKEN)
b=Button(f,fg="red", text="C",padx=30,pady=15,font="lucida 20 bold")
b.pack(side=LEFT,padx=5,pady=2)
b.bind("<Button-1>",click)
b=Button(f,fg="red", text="=",padx=40,pady=15,font="lucida 20 bold")
b.pack(side=LEFT,padx=5,pady=2)
b.bind("<Button-1>",click)
f.pack()

root.mainloop()

